version: '3'

services:
  local-forwarder:
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: "${APPINSIGHTS_INSTRUMENTATIONKEY}"
    build: 
      context: ./lf
  go-app:
    environment: 
      OCAGENT_TRACE_EXPORTER_ENDPOINT: local-forwarder:55678
      SERVICE_NAME: go-app
    build: 
      context: ./go
    ports:
      - "8001:50030"
  python-app:
    environment: 
      OCAGENT_TRACE_EXPORTER_ENDPOINT: local-forwarder:55678  
      SERVICE_NAME: python-app      
    build: 
      context: ./python
    ports:
      - "8002:8000"
  aspnetcore-app:
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: "${APPINSIGHTS_INSTRUMENTATIONKEY}"
      WEBSITE_HOSTNAME: aspnetcore-app
    build: 
      context: ./aspnetcore
    ports:
      - "8003:80"
