FROM python:3.6

RUN apt-get update && apt-get install -y \
  libpq-dev \
  python-dev 
  
ENV PYTHONUNBUFFERED 1


RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
ADD opencensus-0.1.6-py2.py3-none-any.whl /code/
ADD . /code/

RUN pip install -r requirements.txt
RUN pip install opencensus-0.1.6-py2.py3-none-any.whl

EXPOSE 8000

CMD /bin/bash -c 'python3 manage.py runserver 0.0.0.0:8000'